/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.primusdesktopclient.ui;

import com.primusdesktopclient.enums.DayOfWeek;
import com.primusdesktopclient.enums.DepartmentNameEnum;
import com.primusdesktopclient.gsondata.Lecture;
import com.primusdesktopclient.service.UIService;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ocheja Patrick Ileanwa
 */
public class LecturesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnrollJPanel
     */
    public LecturesJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lecturesViewBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lecturesTable = new javax.swing.JTable();
        departmentCB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        dotw = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Select Department");

        lecturesViewBtn.setText("VIEW");
        lecturesViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturesViewBtnActionPerformed(evt);
            }
        });

        lecturesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "LOCATION", "COURSE TITLE (CODE)", "STATUS", "START TIME", "END TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(lecturesTable);
        lecturesTable.getColumnModel().getColumn(0).setMinWidth(150);
        lecturesTable.getColumnModel().getColumn(1).setMinWidth(250);

        departmentCB.setModel(new javax.swing.DefaultComboBoxModel(DepartmentNameEnum.values()));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("CURRENT ONGOING LECTURES");

        dotw.setModel(new javax.swing.DefaultComboBoxModel(DayOfWeek.values()));

        jLabel3.setText("Day of the Week");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lecturesViewBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dotw, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(departmentCB, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(departmentCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dotw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lecturesViewBtn)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lecturesViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturesViewBtnActionPerformed
        // TODO add your handling code here:
        String dept = departmentCB.getSelectedItem().toString();
        String dayoftheweek = dotw.getSelectedItem().toString();
        if (dept != null && dayoftheweek != null) {
            DefaultTableModel defaultTableModel = (DefaultTableModel) lecturesTable.getModel();
            int i = defaultTableModel.getRowCount();
            if (i != 0) {
                for (int j =i-1; j>0; j--) {
                    defaultTableModel.removeRow(j);
                }
            }
            List<Lecture> lectures = new UIService().getLectures(dept, dayoftheweek);
            if (lectures != null) {
                for (Lecture lecture : lectures) {
                    Object[] data = {lecture.getLocation(), lecture.getCourseCodeTitle(),
                        lecture.getStatus().name().replaceAll("_", " "), lecture.getStartTime(), lecture.getEndTime()};
                    defaultTableModel.addRow(data);
                }
                LecturesJPanel.lecturesTable.setModel(defaultTableModel);
            } else {
                JOptionPane.showMessageDialog(null, "No Lectures Found for " + dayoftheweek.toLowerCase(), "No Result Found", JOptionPane.ERROR_MESSAGE);

            }
        }

    }//GEN-LAST:event_lecturesViewBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox departmentCB;
    private javax.swing.JComboBox dotw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable lecturesTable;
    private javax.swing.JButton lecturesViewBtn;
    // End of variables declaration//GEN-END:variables
}
